### ISSUE TITLE
[Bug]: ] local runtime environment daprd bind 55555 tcp port, no cmd clean up runtime resource, led to kanto environment setup failed.

### ISSUE THREAD

**Issue by Yanxshi** [eclipse-velocitas/vehicle-app-python-template#218]
### Severity

Critical

### What release version, tag or commit-hash did you use?

v 0.1.0

### Current Behavior

when Iexec kanto Runtime - UP, this error would be reported

### Steps to Reproduce

none

### Expected Behavior

As described in the title， we need a clean up command to obtain a clean environment

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by MP91** [comment]
Hey @Yanxshi,
do I understand your issue correctly, that you started the local runtime, stopped it again and than tried to start the kanto runtime?

If so, we already have this on the radar. Somehow VS Code got an update, since in the past the local runtime and all the containers were properly stopped when terminating the task.

We will try to fix this, but in the meantime you can also manually stop the containers with the docker extension (docker logo on the sidebar). There you see the running containers at the top and can stop mosquitto, databroker and mockservice.

Sorry for the inconvenience.

**Comment by MP91** [comment]
Since we added the new task for local runtime down and there is no response for some time, we assume this issue is fixed.

@Yanxshi  please open a new issue if you notice something else
